// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA461cxI-Lva0i_wYXkKra98Q45mzpYoFw',
    appId: '1:1047069322245:web:731817320bc1a4b7aa806c',
    messagingSenderId: '1047069322245',
    projectId: 'huttcor-fit',
    authDomain: 'huttcor-fit.firebaseapp.com',
    storageBucket: 'huttcor-fit.firebasestorage.app',
    measurementId: 'G-WHQVYG1QXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXIF5N4wVtf1AEC8CWYxmCWEsEcs3bS8',
    appId: '1:1047069322245:android:6a5f062a0e22f2bfaa806c',
    messagingSenderId: '1047069322245',
    projectId: 'huttcor-fit',
    storageBucket: 'huttcor-fit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqBqgZINOxA4SecLC12JU2zxhzdUsoGw',
    appId: '1:1047069322245:ios:7189291ee84bf068aa806c',
    messagingSenderId: '1047069322245',
    projectId: 'huttcor-fit',
    storageBucket: 'huttcor-fit.firebasestorage.app',
    iosBundleId: 'com.example.huttcorfitApp',
  );
}
